### ISSUE TITLE
packet.mangle

### ISSUE THREAD

**Issue by mohsinahm** [notti/fnfqueue#6]
Hi there, 

thank you for software, this is great replacement for NetfilterQueue which seems discontinued for Python3.7+ version. while i was using the code in my test script for mangling packets I ran into typeerror issue: expected new array length or list/tuple/str, not IP

including my test script and error details, could be I'm something very basic

![image](https://user-images.githubusercontent.com/35180333/106380425-22a11580-63d8-11eb-8bdc-527f5b6c8f81.png)

![image](https://user-images.githubusercontent.com/35180333/106380443-3c425d00-63d8-11eb-8f95-8d92090df3b8.png)

**Comment by notti** [comment]
Looks like you forgot to convert the packet back to bytes. Have a look at
https://github.com/notti/fnfqueue/blob/b8c19507e7b2d71c709f73da84023ab0dfc82096/examples/fnfqueue_add0.py#L23

**Comment by mohsinahm** [comment]
I missed it, that helped me fix the problem, thank you much
